import type { EventBrief } from "../types";
import type { OccasionId } from "./occasions";
import type { GalleryExample } from "./types";

/** English twin of `content.uk.ts`. Same ids, same order, same shape —
 *  `gallery.test.ts` and the `i18n.test.ts` parity walk both hold that.
 *
 *  Written as English rather than translated from the Ukrainian: an invitation
 *  is a small piece of writing, and a line-by-line rendering of one language's
 *  phrasing reads as a rendering. What has to match is the *tone* each id
 *  promises, not the sentences. */
function brief(event_type: string, hosts: string[], tone: string): EventBrief {
  return {
    event_type,
    hosts,
    date: null,
    time: null,
    venue: null,
    city: null,
    tone,
    language: "en",
    extra_details: null,
  };
}

export const GALLERY_EN: Partial<Record<OccasionId, GalleryExample[]>> = {
  wedding: [
    {
      id: "wedding-romantic",
      style: "Romantic",
      styleNote: "Handwritten display, warm pastels",
      sentence: "Olena and Andrii are getting married and inviting family and friends",
      brief: brief("wedding", ["Olena", "Andrii"], "romantic"),
      copy: {
        title: "We're getting married!",
        greeting: "Dear family and friends,",
        body: "We would love you to be with us on the day we say yes to each other.",
        details_line: "We'll share the date and place personally",
        rsvp_prompt: "Let us know if you can be there.",
        closing: "Olena & Andrii",
      },
    },
    {
      id: "wedding-formal",
      style: "Formal",
      styleNote: "Banner heading, classic wording",
      sentence: "A formal wedding invitation from Olena and Andrii to their guests",
      brief: brief("wedding", ["Olena", "Andrii"], "formal"),
      copy: {
        title: "Olena and Andrii invite you",
        greeting: "Dear guests,",
        body: "We would be honoured to have you among the people closest to us on our wedding day.",
        details_line: "Details of the ceremony will follow",
        rsvp_prompt: "Kindly confirm your attendance.",
        closing: "The Koval and Melnyk families",
      },
    },
    {
      id: "wedding-festive",
      style: "Festive",
      styleNote: "Left-aligned text, deep accent",
      sentence: "A big wedding party with music and dancing, inviting all our friends",
      brief: brief("wedding", ["Olena", "Andrii"], "festive"),
      copy: {
        title: "Olena and Andrii's wedding",
        greeting: "Dear friends!",
        body: "We're gathering everyone we love for a celebration we've waited a long time for. There will be music, dancing and a great deal of joy.",
        details_line: "The date and place are coming very soon",
        rsvp_prompt: "Tell us if you're celebrating with us.",
        closing: "See you there!",
      },
    },
    {
      id: "wedding-minimal",
      style: "Minimal",
      styleNote: "No ornament, short and modern",
      sentence: "A short modern wedding invitation with no extra words",
      brief: brief("wedding", ["Olena", "Andrii"], "modern"),
      copy: {
        title: "Our wedding is coming",
        greeting: "Hello!",
        body: "We're getting married and we really want you there. Details to follow shortly.",
        details_line: "We'll announce the date soon",
        rsvp_prompt: "Reply whenever you're ready.",
        closing: "Olena + Andrii",
      },
    },
  ],

  birthday: [
    {
      id: "birthday-warm",
      style: "Warm",
      styleNote: "Homely tone, classic layout",
      sentence: "Celebrating my birthday at home with family and close friends",
      brief: brief("birthday", ["Olena"], "warm"),
      copy: {
        title: "I'm having a birthday",
        greeting: "My dears,",
        body: "I'd like to get everyone I love around one table. Good food, no rush, and plenty of time to talk.",
        details_line: "I'll share the date and place personally",
        rsvp_prompt: "Let me know if you can come.",
        closing: "With love, Olena",
      },
    },
    {
      id: "birthday-formal",
      style: "Formal",
      styleNote: "Banner heading, festive colours",
      sentence: "A milestone birthday, inviting colleagues and friends",
      brief: brief("birthday", ["Olena"], "formal"),
      copy: {
        title: "You are invited to my birthday",
        greeting: "Dear friends and colleagues,",
        body: "This year's date is a particular one, and I would be glad to spend the evening in your company.",
        details_line: "Details of the evening will follow",
        rsvp_prompt: "Please confirm your attendance.",
        closing: "With thanks, Olena Koval",
      },
    },
    {
      id: "birthday-playful",
      style: "Relaxed",
      styleNote: "Bright and simple",
      sentence: "A simple birthday party in the garden, come if you can",
      brief: brief("birthday", ["Olena"], "relaxed"),
      copy: {
        title: "It's my birthday — come along!",
        greeting: "Hi everyone!",
        body: "No schedule and no ties. Music, something good to eat and decent company is the whole plan.",
        details_line: "When and where — very soon",
        rsvp_prompt: "Let me know if you're in.",
        closing: "See you there!",
      },
    },
    {
      id: "birthday-minimal",
      style: "Minimal",
      styleNote: "As few words as possible",
      sentence: "A short birthday invitation with no extra words",
      brief: brief("birthday", ["Olena"], "understated"),
      copy: {
        title: "Birthday",
        greeting: "Hello!",
        body: "I'm marking the day and would be glad to see you.",
        details_line: "I'll announce the date shortly",
        rsvp_prompt: "Reply when you can.",
        closing: "Olena",
      },
    },
  ],

  kids: [
    {
      id: "kids-playful",
      style: "Bright",
      styleNote: "Banner heading, children's colours",
      sentence: "My daughter's birthday, with cake, games and lots of children",
      brief: brief("children's birthday", ["Milana"], "bright"),
      copy: {
        title: "Milana is turning 7!",
        greeting: "Dear friends!",
        body: "Come and celebrate with us — cake, games and a great deal of laughing.",
        details_line: "We'll say when and where very soon",
        rsvp_prompt: "Tell us if you're bringing the children.",
        closing: "The Hnatiuk family",
      },
    },
    {
      id: "kids-warm",
      style: "Warm",
      styleNote: "Calm, for a small gathering",
      sentence: "A cosy children's party for our closest friends and their children",
      brief: brief("children's birthday", ["Milana"], "warm"),
      copy: {
        title: "Milana's birthday",
        greeting: "Dear friends,",
        body: "A small gathering — the children can play while the rest of us finally get to talk.",
        details_line: "We'll share the date and place personally",
        rsvp_prompt: "Let us know how many of you are coming.",
        closing: "See you soon!",
      },
    },
    {
      id: "kids-formal",
      style: "Festive",
      styleNote: "Deep colours, the full text",
      sentence: "A child's birthday party at a cafe with an entertainer",
      brief: brief("children's birthday", ["Milana"], "festive"),
      copy: {
        title: "Come to Milana's party",
        greeting: "Dear guests,",
        body: "There will be food, games and a proper party from start to finish.",
        details_line: "We'll send the time and address shortly",
        rsvp_prompt: "Please let us know if you can make it.",
        closing: "The Hnatiuk family",
      },
    },
    {
      id: "kids-minimal",
      style: "Simple",
      styleNote: "Short and clear",
      sentence: "A very simple invitation to a child's birthday",
      brief: brief("children's birthday", ["Milana"], "simple"),
      copy: {
        title: "Milana's birthday",
        greeting: "Hello!",
        body: "Milana is turning seven. We'd love to see you and the children.",
        details_line: "We'll confirm the date shortly",
        rsvp_prompt: "Please reply.",
        closing: "The Hnatiuk family",
      },
    },
  ],

  christening: [
    {
      id: "christening-quiet",
      style: "Quiet",
      styleNote: "No ornament, a soft tone",
      sentence: "A quiet family christening for our closest relatives",
      brief: brief("christening", ["Sofiia"], "quiet"),
      copy: {
        title: "Sofiia's christening",
        greeting: "Our dear family,",
        body: "We would like to share this day with the people closest to us.",
        details_line: "We'll share the date and place personally",
        rsvp_prompt: "Let us know if you can be there.",
        closing: "The Tkachenko family",
      },
    },
    {
      id: "christening-formal",
      style: "Formal",
      styleNote: "Classic layout, addressed to godparents",
      sentence: "A christening invitation to the godparents and relatives",
      brief: brief("christening", ["Sofiia"], "formal"),
      copy: {
        title: "You are invited to a christening",
        greeting: "Dear family and godparents,",
        body: "It matters to us that the people who will walk beside our daughter are with us on this day.",
        details_line: "Details will follow",
        rsvp_prompt: "Please confirm your attendance.",
        closing: "With gratitude, the Tkachenko family",
      },
    },
    {
      id: "christening-warm",
      style: "Warm",
      styleNote: "Handwritten display, homely tone",
      sentence: "A warm christening invitation for friends and family",
      brief: brief("christening", ["Sofiia"], "warm"),
      copy: {
        title: "Our Sofiia is being christened",
        greeting: "Dear ones,",
        body: "We'd like you to spend this day with us — calmly, warmly, and at home.",
        details_line: "We'll tell you the date and place ourselves",
        rsvp_prompt: "Write and tell us if you'll be with us.",
        closing: "Mariia and Ivan",
      },
    },
    {
      id: "christening-romantic",
      style: "Gentle",
      styleNote: "Left-aligned text, soft palette",
      sentence: "A gentle christening invitation with a short text",
      brief: brief("christening", ["Sofiia"], "gentle"),
      copy: {
        title: "Our daughter's christening",
        greeting: "Dear friends,",
        body: "A small person is taking her first step, and we would be glad to have you close by.",
        details_line: "We'll confirm the date shortly",
        rsvp_prompt: "Let us know if you'll join us.",
        closing: "Mariia and Ivan",
      },
    },
  ],

  corporate: [
    {
      id: "corporate-formal",
      style: "Formal",
      styleNote: "Banner heading, restrained colours",
      sentence: "A formal company evening for the team and our partners",
      brief: brief("company party", ["The team"], "formal"),
      copy: {
        title: "You are invited to our company evening",
        greeting: "Dear colleagues,",
        body: "We'll look back on the year and thank one another for the work behind it.",
        details_line: "The time and place will follow",
        rsvp_prompt: "Please confirm your attendance.",
        closing: "With thanks, the management",
      },
    },
    {
      id: "corporate-festive",
      style: "Festive",
      styleNote: "Deep palette, end-of-year tone",
      sentence: "An end-of-year company party with dinner and music",
      brief: brief("company party", ["The team"], "festive"),
      copy: {
        title: "Our end-of-year party",
        greeting: "Dear colleagues!",
        body: "Dinner, music, and at last a chance to talk about something other than work.",
        details_line: "We'll announce the date and place shortly",
        rsvp_prompt: "Tell us if you're joining.",
        closing: "See you there!",
      },
    },
    {
      id: "corporate-minimal",
      style: "Minimal",
      styleNote: "Short, nothing spare",
      sentence: "A short invitation to colleagues for a team get-together",
      brief: brief("company party", ["The team"], "understated"),
      copy: {
        title: "Team get-together",
        greeting: "Colleagues,",
        body: "We're getting together — informally, and with no presentations.",
        details_line: "We'll confirm the date shortly",
        rsvp_prompt: "Let us know if you're coming.",
        closing: "The team",
      },
    },
    {
      id: "corporate-warm",
      style: "Warm",
      styleNote: "Left-aligned text, thanks to the team",
      sentence: "A warm invitation to the team to celebrate finishing a project",
      brief: brief("company party", ["The team"], "warm"),
      copy: {
        title: "Let's celebrate this together",
        greeting: "Dear team,",
        body: "We did it — and that deserves marking properly, with everyone there.",
        details_line: "We'll confirm the date and place separately",
        rsvp_prompt: "Please confirm you're coming.",
        closing: "With thanks for this year's work",
      },
    },
  ],

  jubilee: [
    {
      id: "jubilee-festive",
      style: "Festive",
      styleNote: "Deep colours, a celebratory tone",
      sentence: "A sixtieth anniversary, gathering family and friends",
      brief: brief("anniversary", ["Mariia"], "festive"),
      copy: {
        title: "Sixty years!",
        greeting: "Dear family and friends,",
        body: "Round numbers don't come round often, and this one deserves the people I love around me.",
        details_line: "We'll confirm the date and place shortly",
        rsvp_prompt: "Please confirm your attendance.",
        closing: "With love, Mariia",
      },
    },
    {
      id: "jubilee-formal",
      style: "Formal",
      styleNote: "Banner heading, classic address",
      sentence: "A formal invitation to an anniversary reception",
      brief: brief("anniversary", ["Mariia"], "formal"),
      copy: {
        title: "An invitation to my anniversary",
        greeting: "Dear guests,",
        body: "I would be glad to spend the evening with the people who have been beside me through these years.",
        details_line: "Details of the occasion will follow",
        rsvp_prompt: "Please confirm your attendance.",
        closing: "With thanks, Mariia Koval",
      },
    },
    {
      id: "jubilee-warm",
      style: "Warm",
      styleNote: "Homely tone, warm palette",
      sentence: "A warm family celebration of an anniversary at home",
      brief: brief("anniversary", ["Mariia"], "warm"),
      copy: {
        title: "Come to my anniversary",
        greeting: "My dears,",
        body: "Nothing grand — one long table, longer conversations, and everyone I love.",
        details_line: "I'll tell you the date and place myself",
        rsvp_prompt: "Write and tell me if you can come.",
        closing: "Your Mariia",
      },
    },
    {
      id: "jubilee-minimal",
      style: "Minimal",
      styleNote: "As few words as possible",
      sentence: "A short, restrained anniversary invitation",
      brief: brief("anniversary", ["Mariia"], "understated"),
      copy: {
        title: "An anniversary",
        greeting: "Hello,",
        body: "I'm marking a round number and would be glad to see you.",
        details_line: "I'll announce the date shortly",
        rsvp_prompt: "Please reply.",
        closing: "Mariia",
      },
    },
  ],
};
